### ISSUE TITLE
@import error - File to import not found or unreadable...

### ISSUE THREAD

**Issue by veeracs** [shakacode/sass-resources-loader#6] opened 2016-02-15 16:59 UTC
When the SCSS file has @import 'bourbon/bourbon'; It's throwing an error, "File to import not found or unreadable: bourbon/bourbon"

Do I need to specify each and every file bourbon imports in the sassResources array from webpack configuration?

in webpack.dev.js

```
var sassLoaders = [
  'style-loader',
  'css-loader?sourceMap',
  'sass-loader',
  'sass-resources'
];

....

  sassResources: [
    path.resolve(projectBase, 'lib/client/assets/styles/app.scss')
  ],
```

In app.scss I have,

```
@import 'bourbon/bourbon';
@import 'base/base';
@import 'helpers/helpers';
@import 'layout/neat/neat';
```

sass-resources-loader is unable to resolve any of the above imports

**Comment by elishaterada** [comment] 2016-03-07 01:01
+1 for automatically handling @import statement within the resource file to load additional resources. 

This is extremely useful with using frameworks like Bootstrap that splits mixins into over 30 files.

Or at least a way to use glob like syntax to specify all mixin files in a directory and such.

**Comment by justin808** [comment] 2016-03-07 08:28
@veeracs @elishaterada Any chance that either of you could make a simple reproduction repository? We'd be very happy to consider a PR for your issues.

**Comment by mirague** [comment] 2016-04-22 09:26
We also find ourselves needing proper support for `@import` statements. Because of the nature of this module we cannot use relative paths, and absolute paths is not an option for us.

**Comment by davidrossjones** [comment] 2016-04-27 06:19
👍 

@justin808 I want to use Foundation with Webpack but the lack of support for the `@import` syntax in a base SCSS file makes this unviable i.e. I'd have to add a direct link to every single mixin file.

I want to:

`npm install foundation-sites`

This will be included globally in my app but I would like access in my modules to Foundation mixins/variables e.g. 

`@include flex-grid-column(12)`

In the webpack config:

`
 sassResources: [
    './node_modules/foundation-sites/scss/foundation.scss'
  ]
`

Unfortunately this does not work because the `foundation.scss` file `@import`s all the mixins recursively across separate files.

Great module but would love the `@import` syntax supported!

**Comment by alexfedoseev** [comment] 2016-05-06 10:41
Sorry guys, somehow I wasn't watching this repo.

Sadly, but such `@import`s significantly slow down hot reloading. It was working this way before, but since these files are actually linked, every change in single component was causing rebuild of the whole css of the app (instead of rebuilding css for just this module). It was super slow. So now I just inline contents of the files w/ resources.

Details: https://github.com/shakacode/sass-resources-loader/issues/4

If anybody has an idea how to make `@import`s work w/o rebuilding whole app's css on each hot update — we are listening.

**Comment by veeracs** [comment] 2016-05-06 10:58
For those who still want this to work,

1 Add the following prop to webpack config,
  `var sassResources = require('./sass-resources');`
  `sassResources: sassResources,`

2. In `sass-resources.js`, 
`module.exports = [
  // Bourbon 4.2.6
  // http://bourbon.io
  // Copyright 2011-2015 thoughtbot, inc.
  // MIT License
  "./lib/client/assets/styles/bourbon/settings/_prefixer.scss",
  "./lib/client/assets/styles/bourbon/settings/_px-to-em.scss",
  "./lib/client/assets/styles/bourbon/settings/_asset-pipeline.scss",
....
];`

**Comment by diegodurli** [comment] 2016-05-12 21:36
Hi guys!

First of all, this is a great loader, helps a lot! My scenario is the following:

I was attempting to use some bourbon mixins within my css-modules files, as @veeracs mentioned.
I thought that it would be hard to explicitly define all paths to Bourbon, therefore I created this small piece of code to load based on patterns:

![image](https://cloud.githubusercontent.com/assets/1239143/15231156/d747ef18-186f-11e6-899b-885b0d5345f4.png)

However, now I faced another problem: I've tried to add resources for **breakpoint-sass**, but these files use @import inside of it, therefore this loader is not able to resolve that.

Do you have any workaround for this situation?

I've tried to define all **breakpoint-sass** mixins files individually but it did not work as well.

**Comment by vict-shevchenko** [comment] 2016-07-20 10:22
Hello, thanks for an awesome plugin. Possibility to correctly handle of ```@impot``` will be also very valuable for my project.

May be its possible to teach saas-resourse-loader understand patterns-matching like:

```
sassResources: {
  files: {
    bourbon: ['path_to_bourbon/**/*.sass', '!_bourbon.sass'],
    myVars: 'styles/vars/*.sass'
  }
}
```

**Comment by justin808** [comment] 2016-08-05 04:18
@diegodurli @vict-shevchenko Does this require a PR?

**Comment by vict-shevchenko** [comment] 2016-08-05 09:38
Yes, this was just a proposition

**Comment by justin808** [comment] 2016-08-05 09:42
@vict-shevchenko If you can provide a sample use case and a PR, we'd consider this.

**Comment by vict-shevchenko** [comment] 2016-08-08 08:26
Sorry, due to a high work load I can commit for this. So any help appreciated.

**Comment by diegodurli** [comment] 2016-08-16 16:50
@justin808 Due to project related changes we moved to another setup, therefore I don't face this use case / scenario anymore

**Comment by justin808** [comment] 2016-08-16 17:20
@vict-shevchenko I think the problem is already solved for you. See https://github.com/shakacode/sass-resources-loader/pull/11

It's in `1.1.0`.

Please confirm and I will close this issue.

**Comment by vict-shevchenko** [comment] 2016-08-16 20:18
Sure, close the issue.  Thanks a lot!

**Closed** 2016-08-16 22:54 UTC
Labels: waiting on submitter
