### ISSUE TITLE
BOM should be removed before concatenating files

### ISSUE THREAD

**Issue by CheeseSucker** [shakacode/sass-resources-loader#36] opened 2017-07-06 10:49 UTC
The UTF8 byte order markers are not removed before the files are glued together.
This means that the BOM ends up in the middle of the scss-document and confuses sass-loader.

Result:
`Invalid CSS after "...ite-2: #ffffff;": expected 1 selector or at-rule, was "﻿"`

**Comment by justin808** [comment] 2017-07-06 22:52
@CheeseSucker Can you please submit a PR with:

1. An example case of reproducing this issue.
2. A fix for this.

CC: @alexfedoseev

**Comment by justin808** [comment] 2018-10-14 20:07
Closing due to inactivity. Please request to reopen if you like. If you can provide a super simple example, on Github, demonstrating the issue, we might be able to help.

**Closed by justin808** 2018-10-14 20:07 UTC
Labels: help wanted, waiting on submitter
